version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    devices:
      - /dev/urandom:/dev/random
    depends_on:
      - mysql
    command: sh -c "sleep 5 ; catalina.sh run"
  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=C5C4ng2ohfry03gG
      - MYSQL_DATABASE=rssfeedagregator
